services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9000:9000"
    env_file: ".env"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_DB}
      NODE_ENV: development
    depends_on:
      - db
    networks:
      - my_network
  db:
    extends:
      file: docker-compose.base.yml
      service: db
    networks:
      - my_network

networks:
  my_network:
    name: my_network
    driver: bridge
