services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9000:9000"
    env_file: ".env"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_DB}
      NODE_ENV: development
    depends_on:
      - db
    networks:
      - my_network
  db:
    image: postgres:latest
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DB: ${DATABASE_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
volumes:
  postgres_data:

networks:
  my_network:
    name: my_network
    driver: bridge
